[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = 'light'


# Primary accent color for interactive elements.
primaryColor = '#fe5f00'


# Background color for the main content area.
backgroundColor = '#ffffff'


# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#eeeeee'


# Color used for almost all text.
textColor = '#262730'


# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = 'sans serif'
